### ISSUE TITLE
typo in tfvars example

### ISSUE THREAD

**Issue by paichl** [tux86/static-website-hosting-amazon-s3#1]
Hi,

Thanks for this brilliant template.
Just a small note - you have a typo in the tfvars example.

domain_name twice; the last one should be tags

**Comment by tux86** [comment]
Hi,
Thank you for your interest in this template.
I apologize for the error on my part. I fixed it. I highly recommend reading the detailed article I've written for this repository. You'll find working tfvars examples there.
Here's the link to the article: https://medium.com/@walid.karray/mastering-static-website-hosting-on-aws-with-terraform-a-step-by-step-tutorial-5401ccd2f4fb
